[32m2025-08-30 21:12:43 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - f43a59dd-4726-4618-8a4a-6995a76322ec - 98935 - LOGS_CAPTURED - Started capturing logs in process (pid: 98935).
[32m2025-08-30 21:12:43 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - f43a59dd-4726-4618-8a4a-6995a76322ec - 98935 - leer_datos - STEP_START - Started execution of step "leer_datos".
[32m2025-08-30 21:12:43 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - f43a59dd-4726-4618-8a4a-6995a76322ec - 98935 - leer_datos - STEP_FAILURE - Execution of step "leer_datos" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "leer_datos"::

FileNotFoundError: [Errno 2] No such file or directory: '/workspace/proyecto-dagster-covid/covid_data.csv'

Stack Trace:
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/ProyectoFinal/src/ProyectoFinal/defs/assets.py", line 16, in leer_datos
    return pd.read_csv(LOCAL_CSV)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
[0m
