[32m2025-08-30 21:35:42 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3a6e14d5-ab7e-4a5c-81a1-d7de7c5293fc - 134495 - LOGS_CAPTURED - Started capturing logs in process (pid: 134495).
[32m2025-08-30 21:35:42 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3a6e14d5-ab7e-4a5c-81a1-d7de7c5293fc - 134495 - metrica_incidencia_7d_chequeos_salida_incidencia - STEP_START - Started execution of step "metrica_incidencia_7d_chequeos_salida_incidencia".
[32m2025-08-30 21:35:42 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3a6e14d5-ab7e-4a5c-81a1-d7de7c5293fc - metrica_incidencia_7d_chequeos_salida_incidencia - Loading file from: /workspaces/Proyecto-dagster-covid/ProyectoFinal/.tmp_dagster_home_q4dabyrq/storage/metrica_incidencia_7d using PickledObjectFilesystemIOManager...
[32m2025-08-30 21:35:42 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3a6e14d5-ab7e-4a5c-81a1-d7de7c5293fc - 134495 - metrica_incidencia_7d_chequeos_salida_incidencia - LOADED_INPUT - Loaded input "metrica_incidencia_7d" using input manager "io_manager", from output "result" of step "metrica_incidencia_7d"
[32m2025-08-30 21:35:42 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3a6e14d5-ab7e-4a5c-81a1-d7de7c5293fc - 134495 - metrica_incidencia_7d_chequeos_salida_incidencia - STEP_INPUT - Got input "metrica_incidencia_7d" of type "DataFrame". (Type check passed).
[32m2025-08-30 21:35:42 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 3a6e14d5-ab7e-4a5c-81a1-d7de7c5293fc - 134495 - metrica_incidencia_7d_chequeos_salida_incidencia - STEP_FAILURE - Execution of step "metrica_incidencia_7d_chequeos_salida_incidencia" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "metrica_incidencia_7d_chequeos_salida_incidencia"::

dagster_shared.check.functions.ParameterCheckError: Param "passed" is not a bool. Got np.True_ which is type <class 'numpy.bool'>.

Stack Trace:
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/ProyectoFinal/src/ProyectoFinal/defs/assets.py", line 175, in chequeos_salida_incidencia
    return dg.AssetCheckResult(
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster/_core/definitions/asset_checks/asset_check_result.py", line 79, in __new__
    passed=check.bool_param(passed, "passed"),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Proyecto-dagster-covid/.venv/lib/python3.12/site-packages/dagster_shared/check/functions.py", line 62, in bool_param
    raise _param_type_mismatch_exception(obj, bool, param_name, additional_message)
[0m
